version: "3"

services:
  hadoopfilecopy:
    image: alako/hadoop
    hostname: hadoopmaster
    container_name: hadoopfilecopy
    restart: "no"
    volumes:
      - ./files/hdfs/master:/var/opt/hdfs # external HDFS directory
      - ./files/hdfs/worker:/var/opt/hdfsworker # worker HDFS for cleaning
      - ./files/data:/data # mount data.json
      - ./hadoop/add-file.sh:/opt/add-file.sh # script
    command:
      - /opt/add-file.sh
