version: "3"

services:
  scala-compiler:
    image: alako/scala_api
    hostname: scala-compiler
    container_name: scala-compiler
    restart: "no"
    volumes:
      - ./scala_api/buildjars.sh:/opt/buildjars.sh # script
      - ./files/jar:/data/jar      # jar location
      - ./scala_api:/data/scala_api # source
        #- ./cosine:/data/cosine # source
    command:
      - /opt/buildjars.sh
