version: '3'

services:
  hadoopmaster:
    image: alako/hadoopmaster
    hostname: hadoopmaster
    container_name: hadoopmaster
    restart: unless-stopped
    ports:
      - '9870:9870' # web monitor
      - '9000:9000' # master slot
        #links:
        #- spark
    volumes:
      - ./hdfs:/var/opt/hdfs
      - ./data:/data

  sparkmaster:
    image: alako/sparkmaster
    hostname: sparkmaster
    container_name: sparkmaster
    restart: unless-stopped
    ports:
      - '8080:8080' # web monitor
      - '7077:7077' # master slot

  sparkworker:
    image: alako/sparkworker
    container_name: sparkworker
    restart: unless-stopped
    depends_on:
      - "hadoopmaster"
      - "sparkmaster"
