version: "3"

services:
  hadoopfilecopy:
    image: alako/hadoop
    hostname: hadoopmaster
    container_name: hadoopfilecopy
    restart: "no"
    volumes:
      - ./hdfs/master:/var/opt/hdfs # external Hadoop File System
      - ./hadoop/add-file.sh:/opt/add-file.sh:ro # get the script
      - ./files/data:/data # get the data
    command:
      - /opt/add-file.sh
