version: "3"

services:
  hadoopmaster:
    image: alako/hadoopmaster
    hostname: hadoopmaster
    container_name: hadoopmaster
    restart: unless-stopped
    ports:
      - "9870:9870" # web monitor
      - "9000:9000" # master slot
    volumes:
      - ./hdfs:/var/opt/hdfs
      - ./data:/data

  sparkmaster:
    image: alako/sparkmaster
    hostname: sparkmaster
    container_name: sparkmaster
    restart: unless-stopped
    ports:
      - "8080:8080" # web monitor
      - "7077:7077" # master slot
      - "9868:9868"

  sparkworker:
    image: alako/sparkworker
    container_name: sparkworker
    restart: unless-stopped
    depends_on:
      - "hadoopmaster"
      - "sparkmaster"
